language: generic

env:
  - MYSQL_IMAGE=mysql:5.5
  - MYSQL_IMAGE=mysql:5.6
  - MYSQL_IMAGE=mysql:5.7
  - POSTGRES_IMAGE=postgres:9.3
  - POSTGRES_IMAGE=postgres:9.4
  - POSTGRES_IMAGE=postgres:9.5
  - POSTGRES_IMAGE=postgres:9.6
  - POSTGRES_IMAGE=postgres:10.4
services:
  - docker

before_install:
  - docker-compose build spec

script:
  - docker-compose run spec
