language: generic

services:
  - docker

before_install:
  - docker-compose build spec

script:
  - docker-compose run spec

env:
  - CURRENT_ADAPTER=mysql
  - CURRENT_ADAPTER=pg
  - CURRENT_ADAPTER=sqlite
