version: '2'
services:
  spec:
    build: .
    command: 'bash -c "cd /app/user && sleep 10 && bin/ameba && crystal tool format --check && crystal spec"'
    working_dir: /app/user
    environment:
      PG_DATABASE_URL: 'postgres://postgres:@pg:5432/postgres'
      MYSQL_DATABASE_URL: 'mysql://user:pass@mysql:3306/test'
      SQLITE_DATABASE_URL: 'sqlite3:./test.db'
      CURRENT_ADAPTER: ${CURRENT_ADAPTER}
    depends_on:
      - pg
      - mysql
  pg:
    image: postgres:${PG_VERSION}
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
